default:
  target: local
  outputs:
    local:
      type: postgres
      method: jdbc
      user: admin
      password: admin
      schema: public # change in dbt_project.yml to staging or curated
      database: jrdb
      host: localhost
      port: 5432
