myprofile:
  target: dev
  outputs:
    dev:
      type: postgres
      method: jdbc
      url: jdbc:postgresql://localhost:5432/mydatabase
      user: myuser
      password: mypassword
      schema: public  # how to use raw/standardized/curated?
      database: mydatabase
      host: localhost
      port: 5432
